# Use Ubuntu 22 as base image
FROM ubuntu:jammy-20250415.1

# Install figlet
RUN apt-get update
RUN apt-get install figlet

# Set default command to run when starting container
CMD figlet My image works!
